runtime: nodejs # For Node.js 8, use runtime: nodejs8
env: flex

manual_scaling:
  instances: 1

network:
  session_affinity: true

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
